# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3cc3683e674261942d2eba764f6f6c9d76cdad8c627e68e27555bd0101a66d6a26ac6bee157eb3879c3e76483b1a37689d010e93637860f9056270c9c3e9d6
  demo_phone_number: "+79991112233"
  demo_code: "12345"

test:
  secret_key_base: 6d1141b937ad4bf11d2acb6453235a568c242fcf229e59a4d057f64dec722577c1588433ba698562c620a2ced049a91cc5750dc3e0109dc1a490b47763efad55
  demo_phone_number: "+79991112233"
  demo_code: "12345"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  demo_phone_number: "<%= ENV["DEMO_PHONE_NUMBER"] %>"
  demo_code: "<%= ENV["DEMO_CODE"] %>"
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  sms_ru_sender: <%= ENV["SMS_RU_SENDER"] %>
  tinkoff_terminal_key: <%= ENV["TINKOFF_TERMINAL_KEY"] %>
  tinkoff_password: <%= ENV["TINKOFF_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  apn_certificate: "<%= ENV["APN_CERTIFICATE"] %>"
  apn_environment: <%= ENV["APN_ENVIRONMENT"] %>
  gcm_api_key: <%= ENV["GCM_API_KEY"] %>
  mailgun_smtp_login: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
  mailgun_smtp_password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
